version: '3'

services:
    mysql:
        image: mysql:latest
        volumes:
            - ./initmysql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: '123456'
            MYSQL_USER: 'spark'
            MYSQL_PASSWORD: '123456'
            MYSQL_DATABASE: 'spark'
        ports:
            - 3307:3306
    postgres:
        image: postgres:alpine
        volumes:
            - ./initpg:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_PASSWORD: '123456'
            POSTGRES_USER: 'spark'
            POSTGRES_PASS: '123456'
            POSTGRES_DB: 'spark'
        ports:
            - 5433:5432
